### ISSUE TITLE
'Vehicle location' does not show up in HUD

### ISSUE THREAD

**Issue by pvajko** [pvajko/courseplay#4]
I've donloaded the file. i've copied to mod folders and nothing. The CP HUD appears as usual, no changes, no posibiliti of choice de vehicle position....

**Comment by pvajko** [comment]
@krambc is this the file you downloaded: https://github.com/pvajko/course-generator/releases/download/v1.0-with-courseplay/ZZZ_courseplay.zip ?
Are you sure there is no other copy of CoursePlay in your mods directory?
Did you click through the 'Starting corner'?
If all of the above is yes, can you post your log.txt?

**Comment by krambc** [comment]
I apologize. It works perfectly. I am embaraced.

**Comment by pvajko** [comment]
No problem. Glad it works.
