### ISSUE TITLE
ROC RT1000 course

### ISSUE THREAD

**Issue by ollydoyle** [pvajko/courseplay#6]
This may not be a issue with courseplay, its more a usage case i think?

There is a new mod of the ROC RT1000, which is a wind-rower, but it has an unusual behaver, were it merges the row to one side instead of the center.
![20170628203730_1](https://user-images.githubusercontent.com/6239276/27656768-24e78b0e-5c42-11e7-9470-a6d7fb0dc070.jpg)
![20170628204037_1](https://user-images.githubusercontent.com/6239276/27656773-2967ec8c-5c42-11e7-9235-394b35c6fa3f.jpg)

So what happens is you get row with 18m spacing (the machine is 9m working width), it  an issue with a auto field generation when the angle change for the 9m an 18m course. maybe it would be a case for selectable angles? is an odd one as you cant use lane offset  of something like that because you would drive into your own bales.

**Comment by pvajko** [comment]
I understand that the generated lane angle is slightly different for 9m and 18m working width. Not sure if this is your problem or something else?

**Comment by ollydoyle** [comment]
No, I'm sure it my problem, your programming, from what if seen in my testing is excellent.

This really falls the realm of a very specific use case, where maybe you shouldn't trouble yourself with accommodating it, given you other plans may solve it 

As for your other plans, it the topic for the stand-alone generator, you asked if selectable angles would be good, for this, they would.

**Comment by pvajko** [comment]
This is moved to the courseplay tracker.
